name: CICD pipeline

on: push

permissions:
  contents: write
  packages: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: action/checkout@v3

      - name: Run test
        run: make test